import lax from 'lax.js'


import './_styleguide'
import './_anime_test'
import './_anime_staggering'
import './_anime_grid'
import './_anime_color_changer'
import './_anime_timeline'
import './_anime_layered'
import './_anime_sphere'
import './_anime_landing'
import './_anime_menu'
import './_anime_hero_001'
import './_array'
import './_plugin_lax'
